import subprocess
from database.schemas.info import InfoResponse


SYSTEM_PROMPT = """
You are VoiceAid AI.

Rules:
- You help with government schemes and public services in India.
- If you are unsure, say you are unsure.
- Do NOT invent scheme names.
- Keep responses short and clear.
- Prefer guidance over assumptions.
"""


def call_ollama(prompt: str) -> str:
    result = subprocess.run(
        ["ollama", "run", "mistral"],
        input=prompt,
        text=True,
        capture_output=True,
        timeout=20,
    )
    return result.stdout.strip()


def handle_llm_fallback(query: str) -> InfoResponse:
    full_prompt = f"{SYSTEM_PROMPT}\nUser question: {query}\nAnswer:"

    answer = call_ollama(full_prompt)

    return InfoResponse(
        success=True,
        source="llm",
        title="General Guidance",
        message=answer,
        summary="This response was generated by the assistant and may not be officially verified.",
    )

