from schemas.info import InfoResponse

def handle_llm_fallback(query: str) -> InfoResponse:
    # Placeholder (actual LLM call later)
    return InfoResponse(
        success=True,
        message="Generated by assistant",
        source="llm",
        title="General Response",
        summary="I'm here to help with government schemes and services."
    )
